/* SPDX-License-Identifier: GPL-3.0-only
 *
 * newlib system-call layer and entry for running rbhost as an AE350 program
 * (software/ae350) on the AE350 + DDR3 image.
 *
 * The codec and the input file are embedded in the image (bench_files.S,
 * generated by the Makefile's bench target) and read from memory.  The
 * output WAV is written to a RAM buffer; its size and CRC-32 (zlib
 * polynomial) are published in the program result registers, so they can
 * be compared with the same decode under qemu-riscv32.  stdout and stderr
 * go to the log ring.
 *
 * Result registers:
 *   USER(0)      rbhost exit status
 *   USER(1,2)    core cycles of main(), low and high word
 *   USER(3,4)    instructions retired in main(), low and high word
 *   USER(5)      output bytes
 *   USER(6)      output CRC-32
 *   USER(7)      input bytes
 *   USER(8,9)    100 MHz fabric time of main(), low and high word
 *   USER(10-12)  RAM-bridge native reads, read-latency sum (100 MHz
 *                cycles), and native writes during main()
 */
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <stdint.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "ae350.h"

#undef errno
extern int errno;

int main(int argc, char **argv);

struct bench_file {
    const char *name;
    const uint8_t *data;
    uint32_t size;
};

extern const struct bench_file bench_files[];
extern const char bench_input_name[];

#define OUTPUT_BASE  ((uint8_t *)0x48000000u)
#define OUTPUT_LIMIT (256u << 20)
#define MAX_FILES    8

static struct {
    const struct bench_file *file;   /* NULL for the output */
    uint32_t position;
    int open;
} files[MAX_FILES];

static uint32_t output_size;
static jmp_buf exit_context;
static int exit_status;

int _open(const char *path, int flags, int mode)
{
    (void)mode;
    for (int fd = 3; fd < MAX_FILES; ++fd) {
        if (files[fd].open)
            continue;
        if ((flags & O_ACCMODE) != O_RDONLY) {
            files[fd].file = NULL;
            files[fd].position = 0;
            files[fd].open = 1;
            if (flags & O_TRUNC)
                output_size = 0;
            return fd;
        }
        for (const struct bench_file *file = bench_files; file->name; ++file) {
            if (!strcmp(file->name, path)) {
                files[fd].file = file;
                files[fd].position = 0;
                files[fd].open = 1;
                return fd;
            }
        }
        errno = ENOENT;
        return -1;
    }
    errno = EMFILE;
    return -1;
}

static int valid_fd(int fd)
{
    if (fd < 3 || fd >= MAX_FILES || !files[fd].open) {
        errno = EBADF;
        return 0;
    }
    return 1;
}

int _close(int fd)
{
    if (!valid_fd(fd))
        return -1;
    files[fd].open = 0;
    return 0;
}

int _read(int fd, void *buffer, size_t count)
{
    if (!valid_fd(fd) || !files[fd].file)
        return -1;
    const struct bench_file *file = files[fd].file;
    uint32_t position = files[fd].position;
    if (position >= file->size)
        return 0;
    if (count > file->size - position)
        count = file->size - position;
    memcpy(buffer, file->data + position, count);
    files[fd].position = position + count;
    return (int)count;
}

int _write(int fd, const void *buffer, size_t count)
{
    if (fd == 1 || fd == 2) {
        for (size_t i = 0; i < count; ++i)
            ae350_putc(((const char *)buffer)[i]);
        return (int)count;
    }
    if (!valid_fd(fd) || files[fd].file)
        return -1;
    uint32_t position = files[fd].position;
    if (count > OUTPUT_LIMIT - position) {
        errno = ENOSPC;
        return -1;
    }
    memcpy(OUTPUT_BASE + position, buffer, count);
    files[fd].position = position + count;
    if (files[fd].position > output_size)
        output_size = files[fd].position;
    return (int)count;
}

off_t _lseek(int fd, off_t offset, int whence)
{
    if (!valid_fd(fd))
        return -1;
    uint32_t size = files[fd].file ? files[fd].file->size : output_size;
    off_t base = whence == SEEK_SET ? 0 :
                 whence == SEEK_CUR ? (off_t)files[fd].position : (off_t)size;
    if (base + offset < 0) {
        errno = EINVAL;
        return -1;
    }
    files[fd].position = (uint32_t)(base + offset);
    return base + offset;
}

int _fstat(int fd, struct stat *st)
{
    memset(st, 0, sizeof(*st));
    st->st_mode = fd <= 2 ? S_IFCHR : S_IFREG;
    st->st_blksize = 4096;
    return 0;
}

int _isatty(int fd)
{
    return fd <= 2;
}

void _exit(int status)
{
    exit_status = status;
    longjmp(exit_context, 1);
}

int _kill(int pid, int signal)
{
    (void)pid;
    (void)signal;
    errno = EINVAL;
    return -1;
}

int _getpid(void)
{
    return 1;
}

extern char __heap_start[];
extern char __heap_end[];

void *_sbrk(ptrdiff_t increment)
{
    static char *brk;
    if (!brk)
        brk = __heap_start;
    if (increment > __heap_end - brk || increment < __heap_start - brk) {
        errno = ENOMEM;
        return (void *)-1;
    }
    char *previous = brk;
    brk += increment;
    return previous;
}

static uint32_t crc32(const uint8_t *data, uint32_t size)
{
    uint32_t crc = 0xffffffffu;
    for (uint32_t i = 0; i < size; ++i) {
        crc ^= data[i];
        for (int bit = 0; bit < 8; ++bit)
            crc = (crc >> 1) ^ (0xedb88320u & -(crc & 1u));
    }
    return ~crc;
}

static void publish64(uint32_t first, uint64_t value)
{
    AE350_REG(AE350_USER(first)) = (uint32_t)value;
    AE350_REG(AE350_USER(first + 1)) = (uint32_t)(value >> 32);
}

/* Nonzero in an image built with BENCH_PLAY=1: after decoding, the output
 * WAV is played through the FPGA player (registers 0x090-0x098).  Each play
 * register write waits while the play FIFO is full, so the loop runs at the
 * player's pace. */
extern const uint32_t bench_play;

static void play_output(void)
{
    const uint8_t *p = OUTPUT_BASE;
    uint32_t n = output_size;

    AE350_REG(AE350_PLAY_CTRL) = 1u;
    for (; n >= 4; p += 4, n -= 4)
        AE350_REG(AE350_PLAY_DATA) = (uint32_t)p[0] | (uint32_t)p[1] << 8 |
                                     (uint32_t)p[2] << 16 | (uint32_t)p[3] << 24;
    for (; n; ++p, --n)
        AE350_REG(AE350_PLAY_BYTE) = *p;
    AE350_REG(AE350_PLAY_CTRL) = 2u;
}

/* Called by crt0_ae350.S after .bss is cleared. */
uint32_t ae350_main(void)
{
    char *argv[] = {"rbhost", "codecs", (char *)bench_input_name, "output.wav", NULL};
    uint32_t input_size = 0;

    for (const struct bench_file *file = bench_files; file->name; ++file)
        if (!strcmp(file->name, bench_input_name))
            input_size = file->size;
    for (int i = 0; i < 16; ++i)
        AE350_REG(AE350_USER(i)) = 0;
    AE350_REG(AE350_USER(7)) = input_size;

    uint32_t reads = AE350_REG(AE350_BRIDGE_READS);
    uint32_t latency = AE350_REG(AE350_BRIDGE_LAT_SUM);
    uint32_t writes = AE350_REG(AE350_BRIDGE_WRITES);
    uint64_t time = ae350_time();
    uint64_t instructions = ae350_instructions();
    uint64_t cycles = ae350_cycles();

    if (setjmp(exit_context) == 0)
        exit_status = main(4, argv);

    cycles = ae350_cycles() - cycles;
    instructions = ae350_instructions() - instructions;
    time = ae350_time() - time;
    AE350_REG(AE350_USER(10)) = AE350_REG(AE350_BRIDGE_READS) - reads;
    AE350_REG(AE350_USER(11)) = AE350_REG(AE350_BRIDGE_LAT_SUM) - latency;
    AE350_REG(AE350_USER(12)) = AE350_REG(AE350_BRIDGE_WRITES) - writes;

    AE350_REG(AE350_USER(0)) = (uint32_t)exit_status;
    publish64(1, cycles);
    publish64(3, instructions);
    AE350_REG(AE350_USER(5)) = output_size;
    AE350_REG(AE350_USER(6)) = crc32(OUTPUT_BASE, output_size);
    publish64(8, time);
    if (bench_play && exit_status == 0)
        play_output();
    return 0x600d0000u | ((uint32_t)exit_status & 0xffffu);
}
