/* SPDX-License-Identifier: GPL-3.0-only
 *
 * newlib system-call layer and entry for running rbhost as an AE350 program
 * (software/ae350) on the AE350 + DDR3 image.
 *
 * The codec and the input file are embedded in the image (bench_files.S,
 * generated by the Makefile's bench target) and read from memory.  The
 * output WAV is written to a RAM buffer; its size and CRC-32 (zlib
 * polynomial) are published in the program result registers, so they can
 * be compared with the same decode under qemu-riscv32.  stdout and stderr
 * go to the log ring.
 *
 * An image built with BENCH_STREAM=2 (make bench-ondemand) is a resident
 * player: it embeds no input and never returns, but asks the BL616 for one
 * track after another and reads each on demand, chunk by chunk, through the
 * file-request mailbox (ae350_request.h).  With BENCH_PLAY=1 it also plays
 * the output as the codec writes it, from a ring in the output buffer, and
 * keeps the play stream open between tracks of the same rate, so a track
 * starts after its first chunks and the next follows without a gap.  See
 * "On-demand input and the resident player" below.
 *
 * Result registers:
 *   USER(0)      rbhost exit status
 *   USER(1,2)    core cycles of main(), low and high word
 *   USER(3,4)    instructions retired in main(), low and high word
 *   USER(5)      output bytes
 *   USER(6)      output CRC-32
 *   USER(7)      input bytes
 *   USER(8,9)    100 MHz fabric time of main(), low and high word
 *   USER(10-12)  RAM-bridge native reads, read-latency sum (100 MHz
 *                cycles), and native writes during main()
 *   USER(13-15)  the file-request mailbox, never cleared here
 */
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <stdint.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "ae350.h"
#include "ae350_request.h"

#undef errno
extern int errno;

int main(int argc, char **argv);
void rbhost_reset(void);

struct bench_file {
    const char *name;
    const uint8_t *data;
    uint32_t size;
};

extern const struct bench_file bench_files[];
extern const char bench_input_name[];
extern const uint32_t bench_stream;

#define OUTPUT_BASE  ((uint8_t *)0x48000000u)
#define OUTPUT_LIMIT (256u << 20)   /* a power of two: also the play ring */
#define INPUT_BASE   ((uint8_t *)0x60000000u)
#define INPUT_LIMIT  (256u << 20)
#define MAX_FILES    8

/* Filled by receive_stream_file(): the streamed input, exposed to the file
 * API under a name that reflects its content so rbhost selects the codec
 * from the extension.  The transport carries only the file bytes, so the
 * extension is probed from the magic bytes instead of the original name. */
static struct bench_file stream_file;
static uint32_t input_stream_size;
static char stream_input_name[16];

static const char *probe_input_extension(const uint8_t *p)
{
	if (!memcmp(p, "fLaC", 4))
		return "flac";
	if (!memcmp(p, "RIFF", 4))
		return "wav";
	if (!memcmp(p, "OggS", 4))
		return !memcmp(p + 28, "OpusHead", 8) ? "opus" : "ogg";
	if (!memcmp(p, "wvpk", 4))
		return "wv";
	if (!memcmp(p, "TTA1", 4))
		return "tta";
	if (p[0] == 0xff && (p[1] & 0xe0) == 0xe0)
		return "mp3";  /* MPEG sync (mp1/mp2/mp3 share the mpa codec) */
	if (!memcmp(p + 4, "ftyp", 4))
		return !memcmp(p + 8, "alac", 4) ? "m4a" : "mp4";
	if (p[0] == 0x30 && p[1] == 0x26 && p[2] == 0xb2 && p[3] == 0x75)
		return "wma";  /* ASF header GUID */
	if (p[0] == 0x0b && p[1] == 0x77)
		return "ac3";
	return "mp3";  /* ID3v2-tagged MP3 and anything unrecognized */
}

static struct {
    const struct bench_file *file;   /* NULL for the output */
    uint32_t position;
    int open;
} files[MAX_FILES];

static uint32_t output_size;
static jmp_buf exit_context;
static int exit_status;

/* Nonzero in an image built with BENCH_PLAY=1 (see play_output and
 * service_output). */
extern const uint32_t bench_play;

/*
 * On-demand input and the resident player (bench_stream == 2).
 *
 * The player does not return after a track.  It asks the BL616 for its next
 * track with a request of length 0 (QUERY_NEXT), which is answered with the
 * track's size, 0 while nothing is queued, or ANSWER_STOP, and then requests
 * the track's bytes in CHUNK_BYTES pieces into INPUT_BASE at the file's own
 * offsets: a chunk a read is waiting for first, otherwise the next missing
 * chunk in order, so the whole file arrives in the background while the codec
 * works and seeks back cost nothing.  While a track decodes it also asks
 * every 100 ms whether to stop it (QUERY_POLL).  One request is outstanding
 * at a time, and its answer is drained from the stream FIFO a little at a
 * time by service(), which every wait and every output write calls, so
 * playback is fed while data arrives.  A stop longjmps out of the codec.
 *
 * Its state is published in the result words: USER(0) RESIDENT_MAGIC,
 * USER(1) tracks begun, USER(2) tracks finished, USER(3) the samples and
 * USER(4) the decode status of the latest finished track (TRACK_ABORTED for
 * one stopped part way).  A track is finished once all of it has been handed
 * to the FPGA player.
 */
#define CHUNK_BYTES   (64u << 10)
#define MAX_CHUNKS    (INPUT_LIMIT / CHUNK_BYTES)
#define DRAIN_BUDGET  256u                      /* stream entries per call */
#define REQUEST_RETRY (2u * AE350_TIME_HZ)      /* silence before asking again */
#define POLL_TICKS    (AE350_TIME_HZ / 10u)
#define IDLE_TICKS    (AE350_TIME_HZ / 20u)     /* between QUERY_NEXTs when idle */

#define QUERY_NEXT     1u
#define QUERY_POLL     2u
#define ANSWER_STOP    0xffffffffu
#define RESIDENT_MAGIC 0x52455331u              /* "RES1" */
#define TRACK_ABORTED  0xffffffffu

static uint8_t chunk_ready[MAX_CHUNKS];
static uint32_t input_chunks;
static uint32_t prefetch_chunk;
static int32_t demand_chunk = -1;
static uint32_t input_requests;
static int decoding;            /* inside main(), where a stop may longjmp */
static int stop_requested;
static uint32_t last_poll;      /* AE350_TIME_LOW at the latest QUERY_POLL */
static struct {
    int active;
    int started;
    int query;                  /* answering a length-0 request */
    uint32_t opcode;
    uint32_t chunk;
    uint32_t received;
    uint32_t answer;
    uint32_t heard;             /* AE350_TIME_LOW at the request or its latest entry */
} rx;

static void service_output(void);

static uint32_t chunk_length(uint32_t chunk)
{
    uint32_t start = chunk * CHUNK_BYTES;
    return input_stream_size - start < CHUNK_BYTES ? input_stream_size - start
                                                   : CHUNK_BYTES;
}

static void begin_request(void)
{
    rx.active = 1;
    rx.started = 0;
    rx.received = 0;
    rx.heard = AE350_REG(AE350_TIME_LOW);
}

static void request_chunk(uint32_t chunk)
{
    begin_request();
    rx.query = 0;
    rx.chunk = chunk;
    ae350_request(chunk * CHUNK_BYTES, chunk_length(chunk));
    ++input_requests;
}

static void request_query(uint32_t opcode)
{
    begin_request();
    rx.query = 1;
    rx.opcode = opcode;
    rx.answer = 0;
    ae350_request(opcode, 0);
}

static void reissue(void)
{
    if (rx.query)
        request_query(rx.opcode);
    else
        request_chunk(rx.chunk);
}

/* Drain the outstanding answer until it is complete or nothing is waiting. */
static void drain_answer(void)
{
    for (uint32_t n = 0; n < DRAIN_BUDGET; ++n) {
        uint32_t status = AE350_REG(AE350_STREAM_STATUS);
        if (!(status & 1u)) {
            /* An answer that never comes is asked for again. */
            if (AE350_REG(AE350_TIME_LOW) - rx.heard > REQUEST_RETRY)
                reissue();
            return;
        }
        uint32_t tag = (status >> 1) & 3u;
        uint32_t data = AE350_REG(AE350_STREAM_DATA);
        AE350_REG(AE350_STREAM_POP) = 0;
        rx.heard = AE350_REG(AE350_TIME_LOW);
        if (tag == AE350_TAG_START) {
            rx.started = 1;
            rx.received = 0;
        } else if (!rx.started) {
            continue;
        } else if (tag == AE350_TAG_DATA) {
            if (rx.query) {
                if (rx.received == 0)
                    rx.answer = data;
            } else if (rx.received < CHUNK_BYTES) {
                /* Chunks start word-aligned; only the file's last chunk ends
                 * in a padded word, inside its own CHUNK_BYTES slot. */
                *(uint32_t *)(INPUT_BASE + rx.chunk * CHUNK_BYTES + rx.received) = data;
            }
            rx.received += 4u;
        } else if (rx.query) {
            if (tag == AE350_TAG_END && data == 4u) {
                rx.active = 0;
                if (rx.opcode == QUERY_POLL && rx.answer == 1u)
                    stop_requested = 1;
            } else {
                reissue();
            }
            return;
        } else {
            /* A short END or a CANCEL leaves the chunk to be asked for
             * again. */
            if (tag == AE350_TAG_END && data == chunk_length(rx.chunk))
                chunk_ready[rx.chunk] = 1;
            rx.active = 0;
            return;
        }
    }
}

static void service_input(void)
{
    if (rx.active) {
        drain_answer();
        if (rx.active)
            return;
    }
    if (decoding && AE350_REG(AE350_TIME_LOW) - last_poll > POLL_TICKS) {
        last_poll = AE350_REG(AE350_TIME_LOW);
        request_query(QUERY_POLL);
        return;
    }
    if (!input_chunks)
        return;
    uint32_t chunk;
    if (demand_chunk >= 0 && !chunk_ready[demand_chunk]) {
        chunk = (uint32_t)demand_chunk;
    } else {
        while (prefetch_chunk < input_chunks && chunk_ready[prefetch_chunk])
            ++prefetch_chunk;
        if (prefetch_chunk >= input_chunks)
            return;
        chunk = prefetch_chunk;
    }
    request_chunk(chunk);
}

static void service(void)
{
    service_input();
    service_output();
    if (decoding && stop_requested)
        longjmp(exit_context, 2);
}

static void wait_for_chunk(uint32_t chunk)
{
    demand_chunk = (int32_t)chunk;
    while (!chunk_ready[chunk])
        service();
    demand_chunk = -1;
}

/* Ask a length-0 question, playing out meanwhile, and return the answer.
 * Used only between tracks, so a played-out stream is ended while waiting. */
static void end_stream_if_played(void);

static uint32_t ask(uint32_t opcode)
{
    while (rx.active) {
        drain_answer();
        service_output();
        end_stream_if_played();
    }
    request_query(opcode);
    while (rx.active) {
        drain_answer();
        service_output();
        end_stream_if_played();
    }
    return rx.answer;
}

/*
 * Live playback (with bench_play).  Each track's output WAV keeps its
 * 0x2e-byte header in track_header and appends its PCM to one stream of
 * positions, held in OUTPUT_BASE as a ring of OUTPUT_LIMIT bytes; the PCM is
 * handed to the FPGA player whenever the play stream has room, never waiting
 * on it, so input keeps being served while the player is full.  The play
 * stream opens half a second in, or at once for a track shorter than that,
 * at the track's rate, and stays open while the next track has the same
 * rate, so tracks follow each other without a gap.  A track at another rate
 * waits for the stream to play out and end, and opens a new one.  Positions
 * are 64-bit so a stream never wraps them.
 */
#define WAV_HEADER_BYTES 0x2eu
#define OUTPUT_MASK      (OUTPUT_LIMIT - 1u)
#define PLAY_PREBUFFER   (44100u * 4u / 2u)
#define WRITE_HEADROOM   (1u << 20)
#define MAX_BOUNDARIES   16u    /* tracks decoded but not yet all handed over */

static uint8_t track_header[WAV_HEADER_BYTES];
static uint32_t track_rate;     /* the current track's, once its PCM begins */
static uint64_t track_base;     /* stream position of its first PCM byte */
static uint64_t pcm_written;    /* stream bytes written ... */
static uint64_t play_position;  /* ... and handed to the player */
static uint32_t stream_rate;    /* the open play stream's rate; 0 for none */
static int output_closed;
static uint32_t tracks_begun;
static uint32_t tracks_finished;
static struct {
    uint64_t end;
    uint32_t samples;
    uint32_t status;
} boundaries[MAX_BOUNDARIES];
static uint32_t boundary_count;

static int live_play(void)
{
    return bench_play && bench_stream == 2u;
}

static uint32_t ring_byte(uint64_t position)
{
    return OUTPUT_BASE[(uint32_t)position & OUTPUT_MASK];
}

static void publish_finished(uint32_t samples, uint32_t status)
{
    ++tracks_finished;
    AE350_REG(AE350_USER(3)) = samples;
    AE350_REG(AE350_USER(4)) = status;
    AE350_REG(AE350_USER(2)) = tracks_finished;
}

static void service_output(void)
{
    if (!live_play())
        return;
    if (!stream_rate) {
        if (!track_rate || pcm_written == play_position ||
            (!output_closed && pcm_written - play_position < PLAY_PREBUFFER))
            return;
        AE350_REG(AE350_PLAY_RATE) = track_rate;
        AE350_REG(AE350_PLAY_CTRL) = 1u;
        stream_rate = track_rate;
    }
    while (play_position + 4u <= pcm_written && (AE350_REG(AE350_PLAY_CTRL) & 1u)) {
        uint64_t p = play_position;
        AE350_REG(AE350_PLAY_DATA) = ring_byte(p) | ring_byte(p + 1u) << 8 |
                                     ring_byte(p + 2u) << 16 | ring_byte(p + 3u) << 24;
        play_position = p + 4u;
    }
    while (boundary_count && play_position >= boundaries[0].end) {
        publish_finished(boundaries[0].samples, boundaries[0].status);
        --boundary_count;
        for (uint32_t i = 0; i < boundary_count; ++i)
            boundaries[i] = boundaries[i + 1u];
    }
}

/* End the play stream once everything written has been handed over. */
static void end_stream_if_played(void)
{
    if (stream_rate && play_position + 4u > pcm_written && !boundary_count) {
        AE350_REG(AE350_PLAY_CTRL) = 2u;
        stream_rate = 0;
    }
}

/* Drop the stream and everything queued for it, for a stop.  Tracks whose
 * audio is dropped still finish, aborted and in order, so the finished count
 * always catches up with the count begun. */
static void play_cancel(void)
{
    if (stream_rate)
        AE350_REG(AE350_PLAY_CTRL) = 4u;
    stream_rate = 0;
    pcm_written = play_position = track_base = 0;
    for (uint32_t i = 0; i < boundary_count; ++i)
        publish_finished(boundaries[i].samples, TRACK_ABORTED);
    boundary_count = 0;
}

/* The output file's bytes: the header to track_header, the PCM to the ring
 * at its stream position, keeping clear of PCM not yet played. */
static void write_output(uint32_t position, const void *buffer, size_t count)
{
    const uint8_t *p = buffer;

    for (; count && position < WAV_HEADER_BYTES; --count)
        track_header[position++] = *p++;
    if (!count)
        return;
    if (!track_rate) {
        uint32_t rate = (uint32_t)track_header[0x18] | (uint32_t)track_header[0x19] << 8 |
                        (uint32_t)track_header[0x1a] << 16 | (uint32_t)track_header[0x1b] << 24;
        if (stream_rate && rate != stream_rate) {
            while (play_position + 4u <= pcm_written)
                service();
            AE350_REG(AE350_PLAY_CTRL) = 2u;
            stream_rate = 0;
        }
        track_rate = rate;
    }
    uint64_t at = track_base + (position - WAV_HEADER_BYTES);
    while (stream_rate && at + count > play_position + OUTPUT_LIMIT - WRITE_HEADROOM)
        service();
    for (uint64_t end = at + count; at < end;) {
        uint32_t offset = (uint32_t)at & OUTPUT_MASK;
        uint32_t run = OUTPUT_LIMIT - offset;
        if (run > end - at)
            run = (uint32_t)(end - at);
        memcpy(OUTPUT_BASE + offset, p, run);
        p += run;
        at += run;
    }
    if (at > pcm_written)
        pcm_written = at;
}

int _open(const char *path, int flags, int mode)
{
    (void)mode;
    for (int fd = 3; fd < MAX_FILES; ++fd) {
        if (files[fd].open)
            continue;
        if ((flags & O_ACCMODE) != O_RDONLY) {
            files[fd].file = NULL;
            files[fd].position = 0;
            files[fd].open = 1;
            if (flags & O_TRUNC)
                output_size = 0;
            return fd;
        }
        if (stream_file.data && !strcmp(stream_file.name, path)) {
            files[fd].file = &stream_file;
            files[fd].position = 0;
            files[fd].open = 1;
            return fd;
        }
        for (const struct bench_file *file = bench_files; file->name; ++file) {
            if (!strcmp(file->name, path)) {
                files[fd].file = file;
                files[fd].position = 0;
                files[fd].open = 1;
                return fd;
            }
        }
        errno = ENOENT;
        return -1;
    }
    errno = EMFILE;
    return -1;
}

static int valid_fd(int fd)
{
    if (fd < 3 || fd >= MAX_FILES || !files[fd].open) {
        errno = EBADF;
        return 0;
    }
    return 1;
}

int _close(int fd)
{
    if (!valid_fd(fd))
        return -1;
    if (!files[fd].file)
        output_closed = 1;
    files[fd].open = 0;
    return 0;
}

int _read(int fd, void *buffer, size_t count)
{
    if (!valid_fd(fd) || !files[fd].file)
        return -1;
    const struct bench_file *file = files[fd].file;
    uint32_t position = files[fd].position;
    if (position >= file->size)
        return 0;
    if (count > file->size - position)
        count = file->size - position;
    if (file == &stream_file && input_chunks && count) {
        uint32_t last = (position + (uint32_t)count - 1u) / CHUNK_BYTES;
        for (uint32_t chunk = position / CHUNK_BYTES; chunk <= last; ++chunk)
            if (!chunk_ready[chunk])
                wait_for_chunk(chunk);
    }
    memcpy(buffer, file->data + position, count);
    files[fd].position = position + count;
    return (int)count;
}

int _write(int fd, const void *buffer, size_t count)
{
    if (fd == 1 || fd == 2) {
        for (size_t i = 0; i < count; ++i)
            ae350_putc(((const char *)buffer)[i]);
        return (int)count;
    }
    if (!valid_fd(fd) || files[fd].file)
        return -1;
    uint32_t position = files[fd].position;
    if (live_play()) {
        write_output(position, buffer, count);
    } else {
        if (count > OUTPUT_LIMIT - position) {
            errno = ENOSPC;
            return -1;
        }
        memcpy(OUTPUT_BASE + position, buffer, count);
    }
    files[fd].position = position + count;
    if (files[fd].position > output_size)
        output_size = files[fd].position;
    if (bench_stream == 2u)
        service();
    return (int)count;
}

off_t _lseek(int fd, off_t offset, int whence)
{
    if (!valid_fd(fd))
        return -1;
    uint32_t size = files[fd].file ? files[fd].file->size : output_size;
    off_t base = whence == SEEK_SET ? 0 :
                 whence == SEEK_CUR ? (off_t)files[fd].position : (off_t)size;
    if (base + offset < 0) {
        errno = EINVAL;
        return -1;
    }
    files[fd].position = (uint32_t)(base + offset);
    return base + offset;
}

int _fstat(int fd, struct stat *st)
{
    memset(st, 0, sizeof(*st));
    st->st_mode = fd <= 2 ? S_IFCHR : S_IFREG;
    if (fd > 2 && fd < MAX_FILES && files[fd].open && files[fd].file)
        st->st_size = files[fd].file->size;
    st->st_blksize = 4096;
    return 0;
}

int _isatty(int fd)
{
    return fd <= 2;
}

void _exit(int status)
{
    exit_status = status;
    longjmp(exit_context, 1);
}

int _kill(int pid, int signal)
{
    (void)pid;
    (void)signal;
    errno = EINVAL;
    return -1;
}

int _getpid(void)
{
    return 1;
}

extern char __heap_start[];
extern char __heap_end[];

void *_sbrk(ptrdiff_t increment)
{
    static char *brk;
    if (!brk)
        brk = __heap_start;
    if (increment > __heap_end - brk || increment < __heap_start - brk) {
        errno = ENOMEM;
        return (void *)-1;
    }
    char *previous = brk;
    brk += increment;
    return previous;
}

static uint32_t crc32(const uint8_t *data, uint32_t size)
{
    uint32_t crc = 0xffffffffu;
    for (uint32_t i = 0; i < size; ++i) {
        crc ^= data[i];
        for (int bit = 0; bit < 8; ++bit)
            crc = (crc >> 1) ^ (0xedb88320u & -(crc & 1u));
    }
    return ~crc;
}

static void publish64(uint32_t first, uint64_t value)
{
    AE350_REG(AE350_USER(first)) = (uint32_t)value;
    AE350_REG(AE350_USER(first + 1)) = (uint32_t)(value >> 32);
}

/* Receive one file through the stream loader entries (START/DATA/END) into
 * INPUT_BASE and register it as the streamed input.  Returns the byte count,
 * or 0 on cancel/error.  DATA words are four little-endian bytes. */
static uint32_t receive_stream_file(void)
{
	uint32_t size = 0;
	int seen_start = 0;

	for (;;) {
		uint32_t status;
		do
			status = AE350_REG(AE350_STREAM_STATUS);
		while (!(status & 1u));
		uint32_t tag = (status >> 1) & 3u;
		uint32_t data = AE350_REG(AE350_STREAM_DATA);
		AE350_REG(AE350_STREAM_POP) = 0;

		if (tag == AE350_TAG_CANCEL)
			return 0;
		if (tag == AE350_TAG_START) {
			seen_start = 1;
			size = 0;
			continue;
		}
		if (!seen_start)
			continue;
		if (tag == AE350_TAG_END) {
			const char *ext = probe_input_extension(INPUT_BASE);
			strcpy(stream_input_name, "input.");
			strcat(stream_input_name, ext);
			stream_file.name = stream_input_name;
			stream_file.data = INPUT_BASE;
			stream_file.size = size;
			input_stream_size = size;
			ae350_puts("stream rx ");
			ae350_put_decimal(size);
			ae350_puts(" first ");
			for (int i = 0; i < 4; ++i) {
				static const char h[] = "0123456789abcdef";
				ae350_putc(h[INPUT_BASE[i] >> 4]);
				ae350_putc(h[INPUT_BASE[i] & 15]);
			}
			ae350_puts("\n");
			return size;
		}
		for (int i = 0; i < 4; ++i) {
			if (size >= INPUT_LIMIT)
				return 0;
			INPUT_BASE[size++] = (uint8_t)data;
			data >>= 8;
		}
	}
}

/* In an image built with BENCH_PLAY=1 and the whole input streamed
 * (bench_stream == 1): after decoding, the output WAV is played through the
 * FPGA player (registers 0x090-0x098).  Each play register write waits while
 * the play FIFO is full, so the loop runs at the player's pace. */

static void play_output(void)
{
    const uint8_t *p = OUTPUT_BASE;
    uint32_t n = output_size;
    uint32_t rate = (uint32_t)p[0x18] | (uint32_t)p[0x19] << 8 |
                    (uint32_t)p[0x1a] << 16 | (uint32_t)p[0x1b] << 24;

    /* Announce the rate, then stream only the PCM body (skip the 0x2e-byte
     * WAV header the FPGA sink no longer parses). */
    AE350_REG(AE350_PLAY_RATE) = rate;
    AE350_REG(AE350_PLAY_CTRL) = 1u;
    p += 0x2e;
    n -= 0x2e;
    for (; n >= 4; p += 4, n -= 4)
        AE350_REG(AE350_PLAY_DATA) = (uint32_t)p[0] | (uint32_t)p[1] << 8 |
                                     (uint32_t)p[2] << 16 | (uint32_t)p[3] << 24;
    for (; n; ++p, --n)
        AE350_REG(AE350_PLAY_BYTE) = *p;
    AE350_REG(AE350_PLAY_CTRL) = 2u;
}

/* Wait for the next track, playing out what is queued and ending the play
 * stream once it has all been handed over; a stop drops it.  Returns the
 * track's size. */
static uint32_t wait_for_track(void)
{
    /* A track is taken only when its end can be recorded. */
    while (boundary_count == MAX_BOUNDARIES)
        service_output();
    for (;;) {
        if (stop_requested) {
            stop_requested = 0;
            play_cancel();
        }
        uint32_t answer = ask(QUERY_NEXT);
        if (answer == ANSWER_STOP) {
            play_cancel();
            continue;
        }
        if (answer && answer <= INPUT_LIMIT)
            return answer;
        uint32_t start = AE350_REG(AE350_TIME_LOW);
        while (AE350_REG(AE350_TIME_LOW) - start < IDLE_TICKS) {
            service_output();
            end_stream_if_played();
        }
    }
}

/* Decode one track of `size` bytes into the play stream. */
static void run_track(uint32_t size)
{
    memset(chunk_ready, 0, sizeof(chunk_ready));
    input_stream_size = size;
    input_chunks = (size + CHUNK_BYTES - 1u) / CHUNK_BYTES;
    prefetch_chunk = 0;
    demand_chunk = -1;
    for (int fd = 3; fd < MAX_FILES; ++fd)
        files[fd].open = 0;
    output_size = 0;
    output_closed = 0;
    track_base = pcm_written;
    track_rate = 0;
    stop_requested = 0;
    exit_status = 0;
    rbhost_reset();
    AE350_REG(AE350_USER(1)) = ++tracks_begun;
    last_poll = AE350_REG(AE350_TIME_LOW);

    if (setjmp(exit_context) == 0) {
        decoding = 1;
        wait_for_chunk(0);
        strcpy(stream_input_name, "input.");
        strcat(stream_input_name, probe_input_extension(INPUT_BASE));
        stream_file.name = stream_input_name;
        stream_file.data = INPUT_BASE;
        stream_file.size = size;
        char *argv[] = {"rbhost", "codecs", stream_input_name, "output.wav", NULL};
        exit_status = main(4, argv);
    }
    decoding = 0;
    input_chunks = 0;
    if (stop_requested) {
        stop_requested = 0;
        play_cancel();
        publish_finished(0, TRACK_ABORTED);
        ae350_puts("track stopped\n");
        return;
    }
    output_closed = 1;
    boundaries[boundary_count].end = pcm_written;   /* a slot is free: wait_for_track */
    boundaries[boundary_count].samples = (uint32_t)((pcm_written - track_base) / 4u);
    boundaries[boundary_count].status = (uint32_t)exit_status;
    ++boundary_count;
    ae350_puts("requests ");
    ae350_put_decimal(input_requests);
    ae350_puts("\n");
}

/* The resident player: one track after another, until the AE350 is restarted. */
static __attribute__((noreturn)) void resident_main(void)
{
    for (int i = 0; i < 13; ++i)
        AE350_REG(AE350_USER(i)) = 0;
    AE350_REG(AE350_USER(0)) = RESIDENT_MAGIC;
    ae350_puts("resident\n");
    for (;;)
        run_track(wait_for_track());
}

/* Called by crt0_ae350.S after .bss is cleared. */
uint32_t ae350_main(void)
{
    uint32_t input_size = 0;

    if (bench_stream == 2u) {
        resident_main();
    } else if (bench_stream) {
        input_size = receive_stream_file();
    } else {
        for (const struct bench_file *file = bench_files; file->name; ++file)
            if (!strcmp(file->name, bench_input_name))
                input_size = file->size;
    }

    char *argv[] = {"rbhost", "codecs",
                    bench_stream ? (char *)stream_file.name
                                 : (char *)bench_input_name,
                    "output.wav", NULL};
    for (int i = 0; i < 13; ++i)
        AE350_REG(AE350_USER(i)) = 0;
    AE350_REG(AE350_USER(7)) = input_size;

    uint32_t reads = AE350_REG(AE350_BRIDGE_READS);
    uint32_t latency = AE350_REG(AE350_BRIDGE_LAT_SUM);
    uint32_t writes = AE350_REG(AE350_BRIDGE_WRITES);
    uint64_t time = ae350_time();
    uint64_t instructions = ae350_instructions();
    uint64_t cycles = ae350_cycles();

    if (setjmp(exit_context) == 0)
        exit_status = main(4, argv);

    cycles = ae350_cycles() - cycles;
    instructions = ae350_instructions() - instructions;
    time = ae350_time() - time;
    AE350_REG(AE350_USER(10)) = AE350_REG(AE350_BRIDGE_READS) - reads;
    AE350_REG(AE350_USER(11)) = AE350_REG(AE350_BRIDGE_LAT_SUM) - latency;
    AE350_REG(AE350_USER(12)) = AE350_REG(AE350_BRIDGE_WRITES) - writes;

    AE350_REG(AE350_USER(0)) = (uint32_t)exit_status;
    publish64(1, cycles);
    publish64(3, instructions);
    AE350_REG(AE350_USER(5)) = output_size;
    AE350_REG(AE350_USER(6)) = output_size <= OUTPUT_LIMIT ? crc32(OUTPUT_BASE, output_size) : 0u;
    publish64(8, time);
    /* The codec's status is nonzero for a trailing error even when the whole
     * track decoded (Opus reports "codec error" after a complete decode), so
     * gate playback on samples actually produced rather than on exit_status. */
    if (bench_play && output_size > 0x2e)
        play_output();
    return 0x600d0000u | ((uint32_t)exit_status & 0xffffu);
}
