// This file is part of Tang-Phosphor.
//
// The AE350 primitive integration is based on LiteX's Gowin AE350 wrapper:
// Copyright (c) 2024 Gwenhael Goavec-Merou <gwenhael@enjoy-digital.fr>
// Copyright (c) 2024-2026 Florent Kermarrec <florent@enjoy-digital.fr>
// SPDX-License-Identifier: BSD-2-Clause

// AE350 hard SoC with its ROM (reset vector 0x80000000), CPU-master extended
// peripheral (EXTS, 0xe8000000), and RAM (DDR_H*) AHB ports brought out to
// fabric.  All bus clocks are bus_clk; the A25 core clock is core_clk, which
// must come from PLL_R[0] CLKOUT1 (see ae350_pll.v).  The internal
// peripherals, APB extension, and fabric master port are unused.
module ae350_soc (
    input  wire         bus_clk,
    input  wire         core_clk,
    input  wire         resetn,

    output wire  [31:0] rom_haddr,
    output wire  [1:0]  rom_htrans,
    input  wire  [31:0] rom_hrdata,
    input  wire         rom_hready,

    output wire  [31:0] exts_haddr,
    output wire         exts_hsel,
    output wire  [1:0]  exts_htrans,
    output wire         exts_hwrite,
    output wire  [2:0]  exts_hsize,
    output wire  [31:0] exts_hwdata,
    input  wire  [31:0] exts_hrdata,
    input  wire         exts_hready,

    output wire  [31:0] ram_haddr,
    output wire  [1:0]  ram_htrans,
    output wire         ram_hwrite,
    output wire  [2:0]  ram_hsize,
    output wire  [2:0]  ram_hburst,
    output wire  [63:0] ram_hwdata,
    input  wire  [63:0] ram_hrdata,
    input  wire         ram_hready,
    input  wire         ram_hresp
);

AE350_SOC cpu (
    .POR_N(1'b1),
    .HW_RSTN(resetn),
    .CORE_CLK(core_clk),
    .DDR_CLK(bus_clk),
    .AHB_CLK(bus_clk),
    .APB_CLK(bus_clk),
    .DBG_TCK(1'b1),
    .RTC_CLK(bus_clk),
    .CORE_CE(1'b1),
    .AXI_CE(1'b1),
    .DDR_CE(1'b1),
    .AHB_CE(1'b1),
    .APB_CE(8'b00000001),
    .APB2AHB_CE(1'b1),
    .PRESETN(),
    .HRESETN(),
    .DDR_RSTN(),

    .GP_INT(16'b0),
    .DMA_REQ(8'b0),
    .DMA_ACK(),
    .CORE0_WFI_MODE(),
    .WAKEUP_IN(1'b0),
    .RTC_WAKEUP(),
    .SCAN_TEST(1'b0),
    .SCAN_EN(1'b0),
    .SCAN_IN(20'hfffff),
    .SCAN_OUT(),
    .TEST_CLK(1'b0),
    .TEST_MODE(1'b0),
    .TEST_RSTN(1'b1),

    .INTEG_TCK(1'b1),
    .INTEG_TDI(1'b1),
    .INTEG_TMS(1'b1),
    .INTEG_TRST(1'b0),
    .INTEG_TDO(),

    .PGEN_CHAIN_I(1'b1),
    .PRDYN_CHAIN_O(),
    .EMA(3'b011),
    .EMAW(2'b01),
    .EMAS(1'b0),
    .RET1N(1'b1),
    .RET2N(1'b1),

    .ROM_HADDR(rom_haddr),
    .ROM_HRDATA(rom_hrdata),
    .ROM_HREADY(rom_hready),
    .ROM_HRESP(1'b0),
    .ROM_HTRANS(rom_htrans),
    .ROM_HWRITE(),

    .APB_PADDR(),
    .APB_PENABLE(),
    .APB_PRDATA(32'b0),
    .APB_PREADY(1'b1),
    .APB_PSEL(),
    .APB_PWDATA(),
    .APB_PWRITE(),
    .APB_PSLVERR(1'b0),
    .APB_PPROT(),
    .APB_PSTRB(),

    .EXTS_HRDATA(exts_hrdata),
    .EXTS_HREADYIN(exts_hready),
    .EXTS_HRESP(1'b0),
    .EXTS_HADDR(exts_haddr),
    .EXTS_HBURST(),
    .EXTS_HPROT(),
    .EXTS_HSEL(exts_hsel),
    .EXTS_HSIZE(exts_hsize),
    .EXTS_HTRANS(exts_htrans),
    .EXTS_HWDATA(exts_hwdata),
    .EXTS_HWRITE(exts_hwrite),

    .EXTM_HADDR(32'b0),
    .EXTM_HBURST(3'b0),
    .EXTM_HPROT(4'b0),
    .EXTM_HRDATA(),
    .EXTM_HREADY(1'b1),
    .EXTM_HREADYOUT(),
    .EXTM_HRESP(),
    .EXTM_HSEL(1'b0),
    .EXTM_HSIZE(3'b0),
    .EXTM_HTRANS(2'b0),
    .EXTM_HWDATA(64'b0),
    .EXTM_HWRITE(1'b0),

    .DDR_HADDR(ram_haddr),
    .DDR_HBURST(ram_hburst),
    .DDR_HPROT(),
    .DDR_HRDATA(ram_hrdata),
    .DDR_HREADY(ram_hready),
    .DDR_HRESP(ram_hresp),
    .DDR_HSIZE(ram_hsize),
    .DDR_HTRANS(ram_htrans),
    .DDR_HWDATA(ram_hwdata),
    .DDR_HWRITE(ram_hwrite),

    .TMS_IN(1'b1),
    .TRST_IN(1'b1),
    .TDI_IN(1'b0),
    .TDO_OUT(),
    .TDO_OE(),

    .SPI2_HOLDN_IN(1'b0),
    .SPI2_WPN_IN(1'b0),
    .SPI2_CLK_IN(1'b0),
    .SPI2_CSN_IN(1'b0),
    .SPI2_MISO_IN(1'b0),
    .SPI2_MOSI_IN(1'b0),
    .SPI2_HOLDN_OUT(),
    .SPI2_HOLDN_OE(),
    .SPI2_WPN_OUT(),
    .SPI2_WPN_OE(),
    .SPI2_CLK_OUT(),
    .SPI2_CLK_OE(),
    .SPI2_CSN_OUT(),
    .SPI2_CSN_OE(),
    .SPI2_MISO_OUT(),
    .SPI2_MISO_OE(),
    .SPI2_MOSI_OUT(),
    .SPI2_MOSI_OE(),

    .I2C_SCL_IN(1'b0),
    .I2C_SDA_IN(1'b0),
    .I2C_SCL(),
    .I2C_SDA(),

    .UART1_TXD(),
    .UART1_RTSN(),
    .UART1_RXD(1'b0),
    .UART1_CTSN(1'b0),
    .UART1_DSRN(1'b0),
    .UART1_DCDN(1'b0),
    .UART1_RIN(1'b0),
    .UART1_DTRN(),
    .UART1_OUT1N(),
    .UART1_OUT2N(),
    .UART2_TXD(),
    .UART2_RTSN(),
    .UART2_RXD(1'b0),
    .UART2_CTSN(1'b1),
    .UART2_DCDN(1'b1),
    .UART2_DSRN(1'b1),
    .UART2_RIN(1'b1),
    .UART2_DTRN(),
    .UART2_OUT1N(),
    .UART2_OUT2N(),

    .CH0_PWM(),
    .CH0_PWMOE(),
    .CH1_PWM(),
    .CH1_PWMOE(),
    .CH2_PWM(),
    .CH2_PWMOE(),
    .CH3_PWM(),
    .CH3_PWMOE(),
    .GPIO_IN(32'b0),
    .GPIO_OE(),
    .GPIO_OUT()
);

endmodule
