#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
#
# Stage the Gowin USB 1.1 SoftPHY used by the full-speed USB host.
#
# Unlike the DDR3 controller, this IP cannot be produced by the batch
# create_ipc/generate_target flow. Its IPSpec declares no projectName and no
# rtlFiles, so generate_target has nothing to emit, and create_ipc registers
# an IP that get_ips never returns a usable handle for. Gowin drives this
# generator from the IP Core Generator dialog instead, whose "Generation
# Config" exposes exactly two choices -- clock frequency (36, 48 or 60 MHz)
# and Disable I/O Insertion -- and whose output is the fixed file set
#
#   usb_softphy_define.v   `define module_name <top> + `define CLK_FREQ<f>
#   usb_softphy_top.v      the UTMI wrapper (from ipcore data/)
#   usb_softphy.vp         the encrypted core   (from ipcore data/)
#   static_macro_define.v  the `getname helper  (from ipcore data/)
#
# This script reproduces that file set from the local Gowin installation, so
# the build stays deterministic and Gowin's generated, encrypted RTL is never
# committed -- the same policy scripts/gen-ddr3-ip.sh follows.
#
# Usage: scripts/gen-usb-phy-ip.sh [IP_DIR] [36|48|60]   (default build/usb-phy-ip 48)

set -euo pipefail

project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ip_dir="$(realpath -m "${1:-$project_dir/build/usb-phy-ip}")"
clk_mhz="${2:-48}"

case "$clk_mhz" in
    36|48|60) ;;
    *) echo "clock frequency must be 36, 48 or 60 (got '$clk_mhz')" >&2; exit 1 ;;
esac

# The SoftPHY input clock is the only generation option. 48 MHz oversamples
# the 12 Mb/s full-speed bit rate four times, which is the conventional choice;
# 36 and 60 MHz exist for designs whose PLL cannot make 48.

gowin_sh_path="${GOWIN_SH:-$(command -v gw_sh || true)}"
if [[ -z "$gowin_sh_path" ]]; then
    for candidate in \
        /home/vash/tools/gowin-1.9.11.03/IDE/bin/gw_sh \
        /opt/Gowin/Gowin_V1.9.11.03/IDE/bin/gw_sh
    do
        if [[ -x "$candidate" ]]; then
            gowin_sh_path="$candidate"
            break
        fi
    done
fi
if [[ -z "$gowin_sh_path" || ! -x "$gowin_sh_path" ]]; then
    echo "Gowin gw_sh not found; set GOWIN_SH to its full path." >&2
    exit 1
fi
gowin_ide="$(cd -- "$(dirname -- "$gowin_sh_path")/.." && pwd)"
ipcore_data="$gowin_ide/ipcore/USBSoftPHY/data"

for f in static_macro_define.v usb_softphy_top.v usb_softphy.vp; do
    if [[ ! -s "$ipcore_data/$f" ]]; then
        echo "missing Gowin SoftPHY file: $ipcore_data/$f" >&2
        exit 1
    fi
done

# Guard against a future or different installation shipping something else
# under the same name: the core must be an IEEE 1735 protected file.
if ! grep -q 'pragma protect' "$ipcore_data/usb_softphy.vp"; then
    echo "$ipcore_data/usb_softphy.vp is not a Gowin protected file" >&2
    exit 1
fi

rm -rf "$ip_dir"
mkdir -p "$ip_dir"
install -m 0644 "$ipcore_data/static_macro_define.v" "$ip_dir/static_macro_define.v"
install -m 0644 "$ipcore_data/usb_softphy_top.v" "$ip_dir/usb_softphy_top.v"
install -m 0644 "$ipcore_data/usb_softphy.vp" "$ip_dir/usb_softphy.vp"

# Single-quoted format: the backticks are literal Verilog macro markers.
{
    printf '// Generated by scripts/gen-usb-phy-ip.sh -- reproduces Gowin'"'"'s\n'
    printf '// USB 1.1 SoftPHY "Generation Config" output. Do not edit; pass a\n'
    printf '// different clock argument to the script instead.\n'
    printf '`define module_name USB_SoftPHY_Top\n'
    printf '`define CLK_FREQ%s\n' "$clk_mhz"
} > "$ip_dir/usb_softphy_define.v"

echo "Staged Gowin USB 1.1 SoftPHY (${clk_mhz} MHz clock) in $ip_dir"
find "$ip_dir" -type f -printf '  %f\n' | sort
